---

- name: Creating host group ansible_ldap from dynamic inventory
  hosts: localhost
  connection: local
  tags: ['install']
  vars:
    fin_tag_name: "{{ tag_name | default('ansible_ldap', true) }}"
    ldap_tag_name : "tag_Name_{{ fin_tag_name | replace('-', '_') }}"
  tasks:
    - add_host: name={{ item }} groups=ldap
      with_items: "{{ groups[ldap_tag_name] }}"

- name: Execute ldap roles
  hosts: ldap
  user: centos
  become: true
  become_method: sudo
  become_user: root
  roles:
    - role: ldap
