---

# roles/ldap/tasks/main.yml
- name: Fail play if the acname name is not defined
  fail: 
    msg: "Specify the acname name: -e 'acname=install'"
  when: acname is undefined
  tags: [install"]

- name: Install openldap
  include: install.yml
  when: acname == "install"
  tags: ["install"]